org: azad123
app: todo-app-project-serverless
service: todo-app-project-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:535201705982:table/Worktodo

functions:
  hello:
    handler: src/hello.handler
    events:
      - httpApi:
          path: /
          method: get
  insertapi:
    handler: src/insertapi.handler
    events:
      - httpApi:
          path: /Work
          method: post
  showapi:
    handler: src/showapi.handler
    events:
      - httpApi:
          path: /Work
          method: get
  completeapi:
    handler: src/completeapi.handler
    events:
      - httpApi:
          path: /Work/{id}
          method: put

resources:
  Resources:
    Worktodo:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Worktodo
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

